# Generated by Django 4.0.1 on 2022-02-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='user_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='report_time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
