# Generated by Django 4.0.1 on 2022-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskreport_user_mail_alter_taskreport_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='next_run_at',
            field=models.DateTimeField(default=None),
        ),
    ]
