# Generated by Django 4.0.1 on 2022-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskreport_next_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
