# Generated by Django 4.0.1 on 2022-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskreport_next_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
